export type LocationType = "hospital" | "treatment-centre";

export type HealthLocation = {
  id: string;
  name: string;
  address: string;
  type: LocationType;
  lat: number;
  lng: number;
};

/** Pin and legend colour per type. Kept beside the data so both stay in step. */
export const LOCATION_COLORS: Record<LocationType, string> = {
  hospital: "#ef4444",
  "treatment-centre": "#3b82f6",
};

export const healthLocations: HealthLocation[] = [
  // ===== SINGAPORE =====
  {
    id: "sg1",
    name: "Singapore General Hospital",
    address: "Outram Road, Singapore 169608",
    type: "hospital",
    lat: 1.2786,
    lng: 103.8347,
  },
  {
    id: "sg2",
    name: "National University Hospital",
    address: "5 Lower Kent Ridge Road, Singapore 119074",
    type: "hospital",
    lat: 1.2944,
    lng: 103.7834,
  },
  {
    id: "sg3",
    name: "Tan Tock Seng Hospital",
    address: "11 Jalan Tan Tock Seng, Singapore 308433",
    type: "hospital",
    lat: 1.3209,
    lng: 103.846,
  },

  // ===== MALAYSIA =====
  {
    id: "my1",
    name: "Hospital Kuala Lumpur",
    address: "Jalan Pahang, 50586 Kuala Lumpur, Malaysia",
    type: "hospital",
    lat: 3.173,
    lng: 101.701,
  },
  {
    id: "my2",
    name: "Penang General Hospital (Hospital Pulau Pinang)",
    address: "Jalan Residensi, George Town, Penang, Malaysia",
    type: "hospital",
    lat: 5.4177,
    lng: 100.3106,
  },
  {
    id: "my3",
    name: "Sultanah Fatimah Specialist Hospital",
    address: "Muar, Johor, Malaysia",
    type: "hospital",
    lat: 2.0442,
    lng: 102.5689,
  },
  {
    id: "my4",
    name: "Hospital Sultanah Nora Ismail",
    address: "Batu Pahat, Johor, Malaysia",
    type: "hospital",
    lat: 1.8548,
    lng: 102.9325,
  },
  {
    id: "my5",
    name: "Hospital Enche Besar Hajjah Kalsom",
    address: "Kluang, Johor, Malaysia",
    type: "hospital",
    lat: 2.0297,
    lng: 103.3178,
  },
  {
    id: "my6",
    name: "Hospital Segamat",
    address: "Segamat, Johor, Malaysia",
    type: "hospital",
    lat: 2.5142,
    lng: 102.8148,
  },
  {
    id: "my7",
    name: "Sultan Ismail Hospital",
    address: "Johor Bahru, Johor, Malaysia",
    type: "hospital",
    lat: 1.5075,
    lng: 103.746,
  },
  {
    id: "my8",
    name: "Hospital Sultanah Aminah",
    address: "Johor Bahru, Johor, Malaysia",
    type: "hospital",
    lat: 1.459,
    lng: 103.759,
  },
  {
    id: "my9",
    name: "Sultanah Bahiyah Hospital",
    address: "Alor Setar, Kedah, Malaysia",
    type: "hospital",
    lat: 6.133,
    lng: 100.367,
  },
  {
    id: "my10",
    name: "Sultan Abdul Halim Hospital",
    address: "Sungai Petani, Kedah, Malaysia",
    type: "hospital",
    lat: 5.646,
    lng: 100.488,
  },
  {
    id: "my11",
    name: "Hospital Raja Perempuan Zainab II",
    address: "Kota Bharu, Kelantan, Malaysia",
    type: "hospital",
    lat: 6.133,
    lng: 102.238,
  },
  {
    id: "my12",
    name: "Hospital Universiti Sains Malaysia (HUSM)",
    address: "Kubang Kerian, Kelantan, Malaysia",
    type: "hospital",
    lat: 6.108,
    lng: 102.266,
  },
  {
    id: "my13",
    name: "University Malaya Medical Centre",
    address: "Lembah Pantai, Kuala Lumpur, Malaysia",
    type: "hospital",
    lat: 3.1191,
    lng: 101.652,
  },
  {
    id: "my14",
    name: "Hospital Canselor Tuanku Muhriz UKM",
    address: "Bandar Tun Razak, Kuala Lumpur, Malaysia",
    type: "hospital",
    lat: 3.122,
    lng: 101.728,
  },
  {
    id: "my15",
    name: "Malacca General Hospital (Hospital Melaka)",
    address: "Melaka, Malaysia",
    type: "hospital",
    lat: 2.1896,
    lng: 102.2501,
  },
  {
    id: "my16",
    name: "Tuanku Ja'afar Hospital",
    address: "Seremban, Negeri Sembilan, Malaysia",
    type: "hospital",
    lat: 2.718,
    lng: 101.95,
  },
  {
    id: "my17",
    name: "Tengku Ampuan Afzan Hospital",
    address: "Kuantan, Pahang, Malaysia",
    type: "hospital",
    lat: 3.813,
    lng: 103.326,
  },
  {
    id: "my18",
    name: "Hospital Sultan Haji Ahmad Shah",
    address: "Temerloh, Pahang, Malaysia",
    type: "hospital",
    lat: 3.452,
    lng: 102.419,
  },
  {
    id: "my19",
    name: "Hospital Seberang Jaya",
    address: "Seberang Jaya, Penang, Malaysia",
    type: "hospital",
    lat: 5.396,
    lng: 100.402,
  },
  {
    id: "my20",
    name: "Hospital Raja Permaisuri Bainun",
    address: "Ipoh, Perak, Malaysia",
    type: "hospital",
    lat: 4.605,
    lng: 101.082,
  },
  {
    id: "my21",
    name: "Teluk Intan Hospital",
    address: "Teluk Intan, Perak, Malaysia",
    type: "hospital",
    lat: 4.025,
    lng: 101.021,
  },
  {
    id: "my22",
    name: "Hospital Taiping",
    address: "Taiping, Perak, Malaysia",
    type: "hospital",
    lat: 4.85,
    lng: 100.738,
  },
  {
    id: "my23",
    name: "Hospital Tuanku Fauziah",
    address: "Kangar, Perlis, Malaysia",
    type: "hospital",
    lat: 6.441,
    lng: 100.199,
  },
  {
    id: "my24",
    name: "Queen Elizabeth Hospital",
    address: "Kota Kinabalu, Sabah, Malaysia",
    type: "hospital",
    lat: 5.97,
    lng: 116.087,
  },
  {
    id: "my25",
    name: "Duchess of Kent Hospital",
    address: "Sandakan, Sabah, Malaysia",
    type: "hospital",
    lat: 5.838,
    lng: 118.117,
  },
  {
    id: "my26",
    name: "Hospital Tawau",
    address: "Tawau, Sabah, Malaysia",
    type: "hospital",
    lat: 4.25,
    lng: 117.894,
  },
  {
    id: "my27",
    name: "Sarawak General Hospital",
    address: "Kuching, Sarawak, Malaysia",
    type: "hospital",
    lat: 1.547,
    lng: 110.359,
  },
  {
    id: "my28",
    name: "Hospital Sibu",
    address: "Sibu, Sarawak, Malaysia",
    type: "hospital",
    lat: 2.287,
    lng: 111.83,
  },
  {
    id: "my29",
    name: "Miri Hospital",
    address: "Miri, Sarawak, Malaysia",
    type: "hospital",
    lat: 4.399,
    lng: 113.991,
  },
  {
    id: "my30",
    name: "Hospital Shah Alam",
    address: "Shah Alam, Selangor, Malaysia",
    type: "hospital",
    lat: 3.073,
    lng: 101.519,
  },
  {
    id: "my31",
    name: "Hospital Selayang",
    address: "Selayang, Selangor, Malaysia",
    type: "hospital",
    lat: 3.257,
    lng: 101.647,
  },
  {
    id: "my32",
    name: "Sungai Buloh Hospital",
    address: "Sungai Buloh, Selangor, Malaysia",
    type: "hospital",
    lat: 3.201,
    lng: 101.562,
  },
  {
    id: "my33",
    name: "Tengku Ampuan Rahimah Hospital",
    address: "Klang, Selangor, Malaysia",
    type: "hospital",
    lat: 3.044,
    lng: 101.45,
  },
  {
    id: "my34",
    name: "Hospital Ampang",
    address: "Ampang, Selangor, Malaysia",
    type: "hospital",
    lat: 3.149,
    lng: 101.762,
  },
  {
    id: "my35",
    name: "Hospital Sultanah Nur Zahirah",
    address: "Kuala Terengganu, Terengganu, Malaysia",
    type: "hospital",
    lat: 5.33,
    lng: 103.14,
  },

  // ===== THAILAND =====
  {
    id: "th1",
    name: "Bumrungrad International Hospital",
    address: "33 Sukhumvit 3, Wattana, Bangkok 10110, Thailand",
    type: "hospital",
    lat: 13.7442,
    lng: 100.5548,
  },
  {
    id: "th2",
    name: "Ramathibodi Hospital",
    address: "270 Rama VI Road, Ratchathewi, Bangkok 10400, Thailand",
    type: "hospital",
    lat: 13.77,
    lng: 100.527,
  },
  {
    id: "th3",
    name: "Rajavithi Hospital",
    address: "Ratchawithi Road, Ratchathewi, Bangkok, Thailand",
    type: "hospital",
    lat: 13.762,
    lng: 100.535,
  },
  {
    id: "th4",
    name: "Lerdsin Hospital",
    address: "Silom Road, Bang Rak, Bangkok, Thailand",
    type: "hospital",
    lat: 13.735,
    lng: 100.515,
  },
  {
    id: "th5",
    name: "Vachira Phuket Hospital",
    address: "Mueang, Phuket, Thailand",
    type: "hospital",
    lat: 7.888,
    lng: 98.393,
  },
  {
    id: "th6",
    name: "Chiang Rai Prachanukroh Hospital",
    address: "Mueang, Chiang Rai, Thailand",
    type: "hospital",
    lat: 19.9105,
    lng: 99.8406,
  },
  {
    id: "th7",
    name: "Maharaj Nakorn Chiang Mai Hospital",
    address: "Mueang, Chiang Mai, Thailand",
    type: "hospital",
    lat: 18.789,
    lng: 98.973,
  },
  {
    id: "th8",
    name: "Khon Kaen Hospital",
    address: "Mueang, Khon Kaen, Thailand",
    type: "hospital",
    lat: 16.4322,
    lng: 102.8236,
  },
  {
    id: "th9",
    name: "Udon Thani Hospital",
    address: "Mueang, Udon Thani, Thailand",
    type: "hospital",
    lat: 17.4139,
    lng: 102.7873,
  },
  {
    id: "th10",
    name: "Hatyai Hospital",
    address: "Hat Yai, Songkhla, Thailand",
    type: "hospital",
    lat: 7.0086,
    lng: 100.4747,
  },
  {
    id: "th11",
    name: "Surat Thani Hospital",
    address: "Mueang, Surat Thani, Thailand",
    type: "hospital",
    lat: 9.1382,
    lng: 99.3215,
  },
  {
    id: "th12",
    name: "Maharat Nakhon Ratchasima Hospital",
    address: "Mueang, Nakhon Ratchasima, Thailand",
    type: "hospital",
    lat: 14.9799,
    lng: 102.0977,
  },
  {
    id: "th13",
    name: "Sunpasitthiprasong Hospital",
    address: "Mueang, Ubon Ratchathani, Thailand",
    type: "hospital",
    lat: 15.2287,
    lng: 104.8551,
  },
  {
    id: "th14",
    name: "Ratchaburi Hospital",
    address: "Mueang, Ratchaburi, Thailand",
    type: "hospital",
    lat: 13.5372,
    lng: 99.8168,
  },
  {
    id: "th15",
    name: "Chaophraya Abhaibhubejhr Hospital",
    address: "Mueang, Prachinburi, Thailand",
    type: "hospital",
    lat: 14.0507,
    lng: 101.3714,
  },
  {
    id: "th16",
    name: "Phra Nakhon Si Ayutthaya Hospital",
    address: "Mueang, Phra Nakhon Si Ayutthaya, Thailand",
    type: "hospital",
    lat: 14.3532,
    lng: 100.568,
  },

  // ===== INDONESIA =====
  {
    id: "id1",
    name: "Cipto Mangunkusumo Hospital (RSCM)",
    address: "Jl. Diponegoro No.71, Jakarta 10430, Indonesia",
    type: "hospital",
    lat: -6.19,
    lng: 106.846,
  },
  {
    id: "id2",
    name: "Dr. Soetomo General Academic Hospital",
    address: "Jl. Mayjen Prof. Dr. Moestopo No. 6-8, Surabaya 60286, Indonesia",
    type: "hospital",
    lat: -7.265,
    lng: 112.752,
  },
  {
    id: "id3",
    name: "RSUP Persahabatan",
    address: "Jl. Persahabatan Raya No. 1, Jakarta Timur, Indonesia",
    type: "hospital",
    lat: -6.193,
    lng: 106.883,
  },
  {
    id: "id4",
    name: "RSUP Fatmawati",
    address: "Jl. RS Fatmawati, Cilandak, Jakarta Selatan, Indonesia",
    type: "hospital",
    lat: -6.294,
    lng: 106.797,
  },
  {
    id: "id5",
    name: "RSPAD Gatot Soebroto",
    address: "Jl. Dr. Abdul Rahman Saleh No. 24, Jakarta Pusat, Indonesia",
    type: "hospital",
    lat: -6.178,
    lng: 106.842,
  },
  {
    id: "id6",
    name: "RSUP Dr. M. Djamil",
    address: "Padang, West Sumatra, Indonesia",
    type: "hospital",
    lat: -0.918,
    lng: 100.367,
  },
  {
    id: "id7",
    name: "RSUD Dr. Achmad Mochtar",
    address: "Bukittinggi, West Sumatra, Indonesia",
    type: "hospital",
    lat: -0.305,
    lng: 100.369,
  },
  {
    id: "id8",
    name: "RSUD Arifin Achmad",
    address: "Jl. Diponegoro No. 2, Pekanbaru, Riau, Indonesia",
    type: "hospital",
    lat: 0.5071,
    lng: 101.4478,
  },
  {
    id: "id9",
    name: "RSUD Dr. M. Yunus",
    address: "Bengkulu, Indonesia",
    type: "hospital",
    lat: -3.7928,
    lng: 102.2607,
  },
  {
    id: "id10",
    name: "RS Bethesda",
    address: "Jl. Jendral Sudirman No 70, Yogyakarta, Indonesia",
    type: "hospital",
    lat: -7.783,
    lng: 110.373,
  },
  {
    id: "id11",
    name: "RSUD Dr. H. Marsidi Judono",
    address: "Tanjungpandan, Belitung, Indonesia",
    type: "hospital",
    lat: -2.741,
    lng: 107.648,
  },
  {
    id: "id12",
    name: "RSUD Depati Hamzah",
    address: "Pangkalpinang, Bangka Belitung, Indonesia",
    type: "hospital",
    lat: -2.133,
    lng: 106.114,
  },
  {
    id: "id13",
    name: "Sanglah General Hospital",
    address: "Denpasar, Bali, Indonesia",
    type: "hospital",
    lat: -8.658,
    lng: 115.217,
  },
  {
    id: "id14",
    name: "RSUD Dr. Zainoel Abidin",
    address: "Banda Aceh, Aceh, Indonesia",
    type: "hospital",
    lat: 5.559,
    lng: 95.318,
  },
  {
    id: "id15",
    name: "RSUP Dr. Kariadi",
    address: "Semarang, Central Java, Indonesia",
    type: "hospital",
    lat: -6.993,
    lng: 110.409,
  },

  // ===== PHILIPPINES =====
  {
    id: "ph1",
    name: "Philippine General Hospital",
    address: "Taft Avenue, Ermita, Manila, Philippines",
    type: "hospital",
    lat: 14.5778,
    lng: 120.9862,
  },
  {
    id: "ph2",
    name: "East Avenue Medical Center",
    address: "East Avenue, Diliman, Quezon City, Philippines",
    type: "hospital",
    lat: 14.644,
    lng: 121.045,
  },
  {
    id: "ph3",
    name: "Jose R. Reyes Memorial Medical Center",
    address: "Rizal Avenue, Sta. Cruz, Manila, Philippines",
    type: "hospital",
    lat: 14.607,
    lng: 120.984,
  },
  {
    id: "ph4",
    name: "Dr. Jose Fabella Memorial Hospital",
    address: "Lope de Vega St., Sta. Cruz, Manila, Philippines",
    type: "hospital",
    lat: 14.608,
    lng: 120.987,
  },
  {
    id: "ph5",
    name: "Rizal Medical Center",
    address: "Pasig City, Philippines",
    type: "hospital",
    lat: 14.572,
    lng: 121.071,
  },
  {
    id: "ph6",
    name: "Amang Rodriguez Memorial Medical Center",
    address: "Sumulong Highway, Sto. Nino, Marikina City, Philippines",
    type: "hospital",
    lat: 14.628,
    lng: 121.101,
  },
  {
    id: "ph7",
    name: "Quirino Memorial Medical Center",
    address: "Quezon City, Philippines",
    type: "hospital",
    lat: 14.635,
    lng: 121.071,
  },
  {
    id: "ph8",
    name: "Valenzuela Medical Center",
    address: "Valenzuela City, Philippines",
    type: "hospital",
    lat: 14.696,
    lng: 120.977,
  },
  {
    id: "ph9",
    name: "Southern Philippines Medical Center",
    address: "Davao City, Philippines",
    type: "hospital",
    lat: 7.073,
    lng: 125.613,
  },
  {
    id: "ph10",
    name: "Vicente Sotto Memorial Medical Center",
    address: "Cebu City, Philippines",
    type: "hospital",
    lat: 10.305,
    lng: 123.9,
  },
  {
    id: "ph11",
    name: "Western Visayas Medical Center",
    address: "Iloilo City, Philippines",
    type: "hospital",
    lat: 10.706,
    lng: 122.562,
  },
  {
    id: "ph12",
    name: "Baguio General Hospital and Medical Center",
    address: "Baguio City, Philippines",
    type: "hospital",
    lat: 16.411,
    lng: 120.599,
  },
  {
    id: "ph13",
    name: "Northern Mindanao Medical Center",
    address: "Cagayan de Oro City, Philippines",
    type: "hospital",
    lat: 8.478,
    lng: 124.647,
  },
  {
    id: "ph14",
    name: "Zamboanga City Medical Center",
    address: "Zamboanga City, Philippines",
    type: "hospital",
    lat: 6.911,
    lng: 122.079,
  },
  {
    id: "ph15",
    name: "Bicol Medical Center",
    address: "Naga City, Philippines",
    type: "hospital",
    lat: 13.621,
    lng: 123.185,
  },

  // ===== VIETNAM =====
  {
    id: "vn1",
    name: "Bach Mai Hospital",
    address: "78 Giai Phong Road, Dong Da, Hanoi, Vietnam",
    type: "hospital",
    lat: 21.0011,
    lng: 105.841,
  },
  {
    id: "vn2",
    name: "Cho Ray Hospital",
    address: "Ho Chi Minh City, Vietnam",
    type: "hospital",
    lat: 10.755,
    lng: 106.66,
  },
  {
    id: "vn3",
    name: "Hue Central Hospital",
    address: "16 Le Loi Street, Vinh Ninh, Hue City, Vietnam",
    type: "hospital",
    lat: 16.464,
    lng: 107.581,
  },
  {
    id: "vn4",
    name: "Da Nang General Hospital",
    address: "124 Hai Phong Street, Hai Chau District, Da Nang, Vietnam",
    type: "hospital",
    lat: 16.068,
    lng: 108.216,
  },
  {
    id: "vn5",
    name: "Viet Tiep International Hospital",
    address: "1 Nha Thuong Street, Le Chan District, Hai Phong, Vietnam",
    type: "hospital",
    lat: 20.85,
    lng: 106.685,
  },
  {
    id: "vn6",
    name: "Lao Cai General Hospital",
    address: "Lao Cai City, Lao Cai Province, Vietnam",
    type: "hospital",
    lat: 22.486,
    lng: 103.97,
  },
  {
    id: "vn7",
    name: "Ha Giang General Hospital",
    address: "Ha Giang City, Ha Giang Province, Vietnam",
    type: "hospital",
    lat: 22.828,
    lng: 104.983,
  },
  {
    id: "vn8",
    name: "Khanh Hoa General Hospital",
    address: "Nha Trang, Khanh Hoa, Vietnam",
    type: "hospital",
    lat: 12.245,
    lng: 109.194,
  },
  {
    id: "vn9",
    name: "General Hospital of Dak Lak",
    address: "Buon Ma Thuot City, Dak Lak, Vietnam",
    type: "hospital",
    lat: 12.666,
    lng: 108.038,
  },
  {
    id: "vn10",
    name: "Ninh Binh Hospital",
    address: "Ninh Binh City, Vietnam",
    type: "hospital",
    lat: 20.253,
    lng: 105.975,
  },
  {
    id: "vn11",
    name: "Vietnam National Children's Hospital",
    address: "Hanoi, Vietnam",
    type: "hospital",
    lat: 21.006,
    lng: 105.823,
  },
  {
    id: "vn12",
    name: "108 Military Central Hospital",
    address: "Hanoi, Vietnam",
    type: "hospital",
    lat: 21.017,
    lng: 105.848,
  },

  // ===== MYANMAR =====
  {
    id: "mm1",
    name: "Yangon General Hospital",
    address: "Lanmadaw, Yangon, Myanmar",
    type: "hospital",
    lat: 16.7789,
    lng: 96.1481,
  },
  {
    id: "mm2",
    name: "Yangon Children's Hospital",
    address: "Yangon, Myanmar",
    type: "hospital",
    lat: 16.796,
    lng: 96.153,
  },
  {
    id: "mm3",
    name: "Thingangyun Sanpya Hospital",
    address: "Thingangyun Township, Yangon, Myanmar",
    type: "hospital",
    lat: 16.809,
    lng: 96.177,
  },
  {
    id: "mm4",
    name: "Yankin Children's Hospital",
    address: "Thitsar Road, Yankin Township, Yangon, Myanmar",
    type: "hospital",
    lat: 16.827,
    lng: 96.166,
  },
  {
    id: "mm5",
    name: "Mandalay General Hospital",
    address: "Mandalay, Myanmar",
    type: "hospital",
    lat: 21.975,
    lng: 96.085,
  },

  // ===== CAMBODIA =====
  {
    id: "kh1",
    name: "Calmette Hospital",
    address: "Phnom Penh, Cambodia",
    type: "hospital",
    lat: 11.576,
    lng: 104.916,
  },
  {
    id: "kh2",
    name: "Khmer-Soviet Friendship Hospital",
    address: "Phnom Penh, Cambodia",
    type: "hospital",
    lat: 11.569,
    lng: 104.92,
  },

  // ===== LAOS =====
  {
    id: "la1",
    name: "Mahosot Hospital",
    address: "Vientiane, Laos",
    type: "hospital",
    lat: 17.964,
    lng: 102.632,
  },

  // ===== BRUNEI =====
  {
    id: "bn1",
    name: "Raja Isteri Pengiran Anak Saleha (RIPAS) Hospital",
    address: "Bandar Seri Begawan, Brunei",
    type: "hospital",
    lat: 4.89,
    lng: 114.942,
  },

  // ===== EAST / SOUTH ASIA =====
  {
    id: "jp1",
    name: "Keio University Hospital",
    address: "35 Shinanomachi, Shinjuku City, Tokyo 160-8582, Japan",
    type: "hospital",
    lat: 35.6836,
    lng: 139.7195,
  },
  {
    id: "jp2",
    name: "Tokyo Medical University Hospital",
    address: "6-7-1 Nishishinjuku, Shinjuku City, Tokyo 160-0023, Japan",
    type: "hospital",
    lat: 35.6938,
    lng: 139.6997,
  },
  {
    id: "jp3",
    name: "Nagoya University Hospital",
    address: "65 Tsurumai-cho, Showa-ku, Nagoya, Aichi 466-8560, Japan",
    type: "hospital",
    lat: 35.156,
    lng: 136.966,
  },
  {
    id: "jp4",
    name: "Hiroshima University Hospital",
    address: "1-2-3 Kasumi, Minami-ku, Hiroshima 734-8551, Japan",
    type: "hospital",
    lat: 34.3835,
    lng: 132.4632,
  },
  {
    id: "kr1",
    name: "Asan Medical Center",
    address: "88 Olympic-ro 43-gil, Songpa-gu, Seoul, South Korea",
    type: "hospital",
    lat: 37.527,
    lng: 127.108,
  },
  {
    id: "kr2",
    name: "Severance Hospital",
    address: "50-1 Yonsei-ro, Seodaemun-gu, Seoul, South Korea",
    type: "hospital",
    lat: 37.5623,
    lng: 126.941,
  },
  {
    id: "kr3",
    name: "Kyung Hee University Hospital",
    address: "23 Kyungheedae-ro, Dongdaemun-gu, Seoul, South Korea",
    type: "hospital",
    lat: 37.5945,
    lng: 127.0517,
  },
  {
    id: "cn1",
    name: "Peking Union Medical College Hospital",
    address: "1 Shuaifuyuan, Dongcheng District, Beijing, China",
    type: "hospital",
    lat: 39.9139,
    lng: 116.4111,
  },
  {
    id: "cn2",
    name: "Beijing Children's Hospital",
    address: "56 Nanlishi Road, Xicheng District, Beijing, China",
    type: "hospital",
    lat: 39.9089,
    lng: 116.362,
  },
  {
    id: "cn3",
    name: "Nanfang Hospital",
    address: "1838 Guangzhou Avenue North, Baiyun District, Guangzhou, China",
    type: "hospital",
    lat: 23.156,
    lng: 113.308,
  },
  {
    id: "cn4",
    name: "Ruijin Hospital",
    address: "197 Ruijin Er Road, Huangpu District, Shanghai, China",
    type: "hospital",
    lat: 31.2131,
    lng: 121.4649,
  },
  {
    id: "cn5",
    name: "Xiangya Hospital",
    address: "87 Xiangya Road, Kaifu District, Changsha, Hunan, China",
    type: "hospital",
    lat: 28.1936,
    lng: 112.977,
  },
  {
    id: "hk1",
    name: "Queen Mary Hospital",
    address: "102 Pok Fu Lam Road, Hong Kong",
    type: "hospital",
    lat: 22.2703,
    lng: 114.1298,
  },
  {
    id: "hk2",
    name: "Prince of Wales Hospital",
    address: "30-32 Ngan Shing Street, Shatin, Hong Kong",
    type: "hospital",
    lat: 22.379,
    lng: 114.202,
  },
  {
    id: "tw1",
    name: "National Taiwan University Hospital",
    address: "No. 7, Zhongshan S. Rd, Zhongzheng District, Taipei, Taiwan",
    type: "hospital",
    lat: 25.041,
    lng: 121.5177,
  },
  {
    id: "in1",
    name: "All India Institute of Medical Sciences (AIIMS)",
    address: "Ansari Nagar, New Delhi 110029, India",
    type: "hospital",
    lat: 28.5672,
    lng: 77.21,
  },
  {
    id: "in2",
    name: "Christian Medical College",
    address: "Vellore, Tamil Nadu 632004, India",
    type: "hospital",
    lat: 12.9246,
    lng: 79.1349,
  },
  {
    id: "in3",
    name: "King Edward Memorial (KEM) Hospital",
    address: "Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012, India",
    type: "hospital",
    lat: 19.0011,
    lng: 72.8419,
  },
  {
    id: "pk1",
    name: "Aga Khan University Hospital",
    address: "Stadium Road, Karachi 74800, Pakistan",
    type: "hospital",
    lat: 24.8927,
    lng: 67.0822,
  },
  {
    id: "lk1",
    name: "National Hospital of Sri Lanka",
    address: "Regent Street, Colombo 08, Sri Lanka",
    type: "hospital",
    lat: 6.9218,
    lng: 79.8621,
  },

  // ===== DEDICATED HAEMOPHILIA TREATMENT CENTRES (blue) =====
  {
    id: "htc1",
    name: "Haemophilia Comprehensive Treatment Centre - SGH",
    address: "Haematology Centre, Singapore General Hospital, Outram Road, Singapore 169608",
    type: "treatment-centre",
    lat: 1.2786,
    lng: 103.8347,
  },
  {
    id: "htc2",
    name: "AIIMS Hemophilia Treatment Centre",
    address: "Department of Haematology, AIIMS, Ansari Nagar, New Delhi 110029, India",
    type: "treatment-centre",
    lat: 28.5672,
    lng: 77.21,
  },
  {
    id: "htc3",
    name: "Christian Medical College Vellore - Haemophilia Care",
    address: "Christian Medical College, Vellore, Tamil Nadu 632004, India",
    type: "treatment-centre",
    lat: 12.9246,
    lng: 79.1349,
  },
  {
    id: "htc4",
    name: "KEM Hospital Haemophilia Care",
    address: "King Edward Memorial Hospital, Parel, Mumbai, Maharashtra 400012, India",
    type: "treatment-centre",
    lat: 19.0011,
    lng: 72.8419,
  },
  {
    id: "htc5",
    name: "St. John's Medical College Hospital - Haematology",
    address: "Sarjapur Road, Bengaluru, Karnataka 560034, India",
    type: "treatment-centre",
    lat: 12.9279,
    lng: 77.6271,
  },
  {
    id: "htc6",
    name: "Hiroshima University Hospital Hemophilia Treatment Center",
    address: "1-2-3 Kasumi, Minami-ku, Hiroshima 734-8551, Japan",
    type: "treatment-centre",
    lat: 34.3835,
    lng: 132.4632,
  },
  {
    id: "htc7",
    name: "Queen Mary Hospital - Hemophilia Care",
    address: "102 Pok Fu Lam Road, Hong Kong",
    type: "treatment-centre",
    lat: 22.2703,
    lng: 114.1298,
  },
  {
    id: "htc8",
    name: "Hospital Kuala Lumpur - Hemophilia Care",
    address: "Jalan Pahang, 50586 Kuala Lumpur, Malaysia",
    type: "treatment-centre",
    lat: 3.173,
    lng: 101.701,
  },
  {
    id: "htc9",
    name: "Severance Hospital - Hemophilia Care",
    address: "50-1 Yonsei-ro, Seodaemun-gu, Seoul, South Korea",
    type: "treatment-centre",
    lat: 37.5623,
    lng: 126.941,
  },
  {
    id: "htc10",
    name: "National Taiwan University Hospital - Hemophilia Care",
    address: "No. 7, Zhongshan S. Rd, Zhongzheng District, Taipei, Taiwan",
    type: "treatment-centre",
    lat: 25.041,
    lng: 121.5177,
  },
  {
    id: "htc11",
    name: "Peking Union Medical College Hospital - Hemophilia Care",
    address: "1 Shuaifuyuan, Dongcheng District, Beijing, China",
    type: "treatment-centre",
    lat: 39.9139,
    lng: 116.4111,
  },
  {
    id: "htc12",
    name: "Beijing Children's Hospital - Hemophilia Care",
    address: "56 Nanlishi Road, Xicheng District, Beijing, China",
    type: "treatment-centre",
    lat: 39.9089,
    lng: 116.362,
  },
  {
    id: "htc13",
    name: "Nanfang Hospital - Hemophilia Care",
    address: "1838 Guangzhou Avenue North, Baiyun District, Guangzhou, China",
    type: "treatment-centre",
    lat: 23.156,
    lng: 113.308,
  },
  {
    id: "htc14",
    name: "Ruijin Hospital - Hemophilia Care",
    address: "197 Ruijin Er Road, Huangpu District, Shanghai, China",
    type: "treatment-centre",
    lat: 31.2131,
    lng: 121.4649,
  },
  {
    id: "htc15",
    name: "Tianjin Institute of Hematology & Blood Diseases Hospital",
    address: "288 Nanjing Road, Heping District, Tianjin, China",
    type: "treatment-centre",
    lat: 39.121,
    lng: 117.202,
  },
  {
    id: "htc16",
    name: "Xiangya Hospital - Hemophilia Care",
    address: "87 Xiangya Road, Kaifu District, Changsha, Hunan, China",
    type: "treatment-centre",
    lat: 28.1936,
    lng: 112.977,
  },
  {
    id: "htc17",
    name: "Prince of Wales Hospital - Hemophilia Care",
    address: "30-32 Ngan Shing Street, Shatin, Hong Kong",
    type: "treatment-centre",
    lat: 22.379,
    lng: 114.202,
  },
  {
    id: "htc18",
    name: "Penang General Hospital - Hemophilia Care",
    address: "Jalan Residensi, George Town, Penang, Malaysia",
    type: "treatment-centre",
    lat: 5.4177,
    lng: 100.3106,
  },
  {
    id: "htc19",
    name: "Ramathibodi Hospital - Hemophilia Care",
    address: "270 Rama VI Road, Ratchathewi, Bangkok 10400, Thailand",
    type: "treatment-centre",
    lat: 13.77,
    lng: 100.527,
  },
  {
    id: "htc20",
    name: "Kyung Hee University Hospital - Hemophilia Care",
    address: "23 Kyungheedae-ro, Dongdaemun-gu, Seoul, South Korea",
    type: "treatment-centre",
    lat: 37.5945,
    lng: 127.0517,
  },
  {
    id: "htc21",
    name: "Tokyo Medical University Hospital - Hemophilia Care",
    address: "6-7-1 Nishishinjuku, Shinjuku City, Tokyo, Japan",
    type: "treatment-centre",
    lat: 35.6938,
    lng: 139.6997,
  },
  {
    id: "htc22",
    name: "Nagoya University Hospital - Hemophilia Care",
    address: "65 Tsurumai-cho, Showa-ku, Nagoya, Aichi, Japan",
    type: "treatment-centre",
    lat: 35.156,
    lng: 136.966,
  },

  // ===== SOUTHEAST ASIA HAEMOPHILIA TREATMENT CENTRES =====
  // Confirmed via clinical trial registries (clinicaltrials.gov) and peer-reviewed
  // haematology literature listing these as active haemophilia treatment/research sites.
  {
    id: "htc23",
    name: "Hospital Ampang - Haemophilia Treatment Centre",
    address: "Jalan Mewah Utara, Ampang, Selangor, Malaysia",
    type: "treatment-centre",
    lat: 3.149,
    lng: 101.762,
  },
  {
    id: "htc24",
    name: "Hospital Raja Perempuan Zainab II - Haemophilia Care",
    address: "Kota Bharu, Kelantan, Malaysia",
    type: "treatment-centre",
    lat: 6.133,
    lng: 102.238,
  },
  {
    id: "htc25",
    name: "Queen Elizabeth Hospital - Haemophilia Care",
    address: "Kota Kinabalu, Sabah, Malaysia",
    type: "treatment-centre",
    lat: 5.97,
    lng: 116.087,
  },
  {
    id: "htc26",
    name: "Hospital Tunku Azizah - Haemophilia Care",
    address: "Kuala Lumpur, Malaysia",
    type: "treatment-centre",
    lat: 3.165,
    lng: 101.694,
  },
  {
    id: "htc27",
    name: "Tuanku Ja'afar Hospital - Haemophilia Care",
    address: "Seremban, Negeri Sembilan, Malaysia",
    type: "treatment-centre",
    lat: 2.718,
    lng: 101.95,
  },
  {
    id: "htc28",
    name: "King Chulalongkorn Memorial Hospital - Paediatric Haematology-Oncology",
    address: "1873 Rama IV Road, Pathumwan, Bangkok 10330, Thailand",
    type: "treatment-centre",
    lat: 13.733,
    lng: 100.533,
  },
  {
    id: "htc29",
    name: "Maharaj Nakorn Chiang Mai Hospital - Haemophilia Care",
    address: "Chiang Mai University, Mueang, Chiang Mai, Thailand",
    type: "treatment-centre",
    lat: 18.789,
    lng: 98.973,
  },
  {
    id: "htc30",
    name: "National Institute of Hematology and Blood Transfusion - Hemophilia Centre",
    address: "Hanoi, Vietnam",
    type: "treatment-centre",
    lat: 21.008,
    lng: 105.82,
  },
  {
    id: "htc31",
    name: "Cipto Mangunkusumo Hospital - Paediatric Haemophilia Care",
    address: "Jl. Diponegoro No.71, Jakarta 10430, Indonesia",
    type: "treatment-centre",
    lat: -6.19,
    lng: 106.846,
  },
];
