import type { TranslationTarget } from "@/lib/api";

/**
 * The card's clinical vocabulary: every diagnosis and severity label in
 * `medical-id.ts`, and the fields they fill. LibreTranslate gets these wrong in
 * most languages — "Severe" came back as "Login" in Japanese and "Main menu"
 * in Korean, and "Haemophilia A" as the bacterium Haemophilus in Chinese — so
 * every language below spells all of them out by hand.
 */
export type MedicalTerm =
  | "Bleeding Disorder"
  | "Blood Type"
  | "Diagnosis"
  | "Severity"
  | "Current Medication"
  | "Drug Allergies"
  | "Allergies"
  | "Haemophilia A"
  | "Haemophilia B"
  | "Factor XI Deficiency"
  | "Acquired Haemophilia"
  | "Symptomatic Carrier (A)"
  | "Symptomatic Carrier (B)"
  | "Severe"
  | "Moderate"
  | "Mild"
  | "Not known"
  | "Severe deficiency"
  | "Partial deficiency"
  | "Life-threatening / major bleeding"
  | "Moderate / non-life-threatening"
  | "Unknown";

/**
 * Hand translations of the card's copy, which win over LibreTranslate.
 *
 * Each language has every `MedicalTerm`, then only the other strings
 * LibreTranslate was seen to get wrong in it (checked on 2026-09-26, locally
 * and on Railway): "Relationship" as "related articles", "Not recorded" as
 * "no audio recording", a button that drops "Call". Anything not listed here
 * is still machine-translated.
 */
export const MEDICAL_ID_GLOSSARY: Record<
  TranslationTarget,
  Record<MedicalTerm, string> & Record<string, string>
> = {
  "zh-Hans": {
    "Bleeding Disorder": "出血性疾病",
    "Blood Type": "血型",
    Diagnosis: "诊断",
    Severity: "严重程度",
    "Current Medication": "当前用药",
    "Drug Allergies": "药物过敏",
    Allergies: "过敏",
    "Haemophilia A": "血友病A",
    "Haemophilia B": "血友病B",
    "Factor XI Deficiency": "凝血因子XI缺乏症",
    "Acquired Haemophilia": "获得性血友病",
    "Symptomatic Carrier (A)": "症状性携带者（血友病A）",
    "Symptomatic Carrier (B)": "症状性携带者（血友病B）",
    Severe: "重型",
    Moderate: "中型",
    Mild: "轻型",
    "Not known": "不详",
    "Severe deficiency": "重度缺乏",
    "Partial deficiency": "部分缺乏",
    "Life-threatening / major bleeding": "危及生命／大出血",
    "Moderate / non-life-threatening": "中度／不危及生命",
    Unknown: "不详",

    "Patient Details": "患者信息",
    Name: "姓名",
    "Primary Doctor (Organisation)": "主治医生（医疗机构）",
    Organisation: "医疗机构",
    "Call Doctor": "致电医生",
    "Yes — details not recorded": "有（未记录详情）",
  },
  "zh-Hant": {
    "Bleeding Disorder": "出血性疾病",
    "Blood Type": "血型",
    Diagnosis: "診斷",
    Severity: "嚴重程度",
    "Current Medication": "目前用藥",
    "Drug Allergies": "藥物過敏",
    Allergies: "過敏",
    "Haemophilia A": "血友病A",
    "Haemophilia B": "血友病B",
    "Factor XI Deficiency": "凝血因子XI缺乏症",
    "Acquired Haemophilia": "後天性血友病",
    "Symptomatic Carrier (A)": "有症狀帶因者（血友病A）",
    "Symptomatic Carrier (B)": "有症狀帶因者（血友病B）",
    Severe: "重度",
    Moderate: "中度",
    Mild: "輕度",
    "Not known": "不詳",
    "Severe deficiency": "嚴重缺乏",
    "Partial deficiency": "部分缺乏",
    "Life-threatening / major bleeding": "危及生命／大量出血",
    "Moderate / non-life-threatening": "中度／不危及生命",
    Unknown: "不詳",

    "Patient Details": "病人資料",
    "Primary Doctor (Organisation)": "主診醫生（醫療機構）",
    Organisation: "醫療機構",
    "Call Doctor": "致電醫生",
    "Yes — details not recorded": "有（未記錄詳情）",
    "Machine-translated from English": "由英文機器翻譯",
  },
  ms: {
    "Bleeding Disorder": "Gangguan Pendarahan",
    "Blood Type": "Kumpulan Darah",
    Diagnosis: "Diagnosis",
    Severity: "Tahap Keterukan",
    "Current Medication": "Ubat Semasa",
    "Drug Allergies": "Alahan Ubat",
    Allergies: "Alahan",
    "Haemophilia A": "Hemofilia A",
    "Haemophilia B": "Hemofilia B",
    "Factor XI Deficiency": "Kekurangan Faktor XI",
    "Acquired Haemophilia": "Hemofilia Perolehan",
    "Symptomatic Carrier (A)": "Pembawa Bergejala (Hemofilia A)",
    "Symptomatic Carrier (B)": "Pembawa Bergejala (Hemofilia B)",
    Severe: "Teruk",
    Moderate: "Sederhana",
    Mild: "Ringan",
    "Not known": "Tidak diketahui",
    "Severe deficiency": "Kekurangan teruk",
    "Partial deficiency": "Kekurangan separa",
    "Life-threatening / major bleeding": "Mengancam nyawa / pendarahan besar",
    "Moderate / non-life-threatening": "Sederhana / tidak mengancam nyawa",
    Unknown: "Tidak diketahui",

    "Handle with Care": "Rawat dengan Berhati-hati",
    "Patient Details": "Butiran Pesakit",
    "Medical Information": "Maklumat Perubatan",
    "Call Doctor": "Hubungi Doktor",
    "Machine-translated from English": "Diterjemah oleh mesin daripada bahasa Inggeris",
  },
  id: {
    "Bleeding Disorder": "Gangguan Perdarahan",
    "Blood Type": "Golongan Darah",
    Diagnosis: "Diagnosis",
    Severity: "Tingkat Keparahan",
    "Current Medication": "Obat Saat Ini",
    "Drug Allergies": "Alergi Obat",
    Allergies: "Alergi",
    "Haemophilia A": "Hemofilia A",
    "Haemophilia B": "Hemofilia B",
    "Factor XI Deficiency": "Defisiensi Faktor XI",
    "Acquired Haemophilia": "Hemofilia Didapat",
    "Symptomatic Carrier (A)": "Pembawa Sifat Bergejala (Hemofilia A)",
    "Symptomatic Carrier (B)": "Pembawa Sifat Bergejala (Hemofilia B)",
    Severe: "Berat",
    Moderate: "Sedang",
    Mild: "Ringan",
    "Not known": "Tidak diketahui",
    "Severe deficiency": "Defisiensi berat",
    "Partial deficiency": "Defisiensi parsial",
    "Life-threatening / major bleeding": "Mengancam jiwa / perdarahan mayor",
    "Moderate / non-life-threatening": "Sedang / tidak mengancam jiwa",
    Unknown: "Tidak diketahui",

    "Handle with Care": "Tangani dengan Hati-hati",
    "Call Doctor": "Hubungi Dokter",
    "Not recorded": "Tidak dicatat",
    "None recorded": "Tidak ada yang dicatat",
    "Yes — details not recorded": "Ya — rincian tidak dicatat",
    "Machine-translated from English": "Diterjemahkan mesin dari bahasa Inggris",
  },
  th: {
    "Bleeding Disorder": "ภาวะเลือดออกผิดปกติ",
    "Blood Type": "หมู่เลือด",
    Diagnosis: "การวินิจฉัย",
    Severity: "ความรุนแรง",
    "Current Medication": "ยาที่ใช้อยู่",
    "Drug Allergies": "การแพ้ยา",
    Allergies: "การแพ้",
    "Haemophilia A": "ฮีโมฟีเลีย เอ",
    "Haemophilia B": "ฮีโมฟีเลีย บี",
    "Factor XI Deficiency": "ภาวะพร่องแฟกเตอร์ 11",
    "Acquired Haemophilia": "ฮีโมฟีเลียชนิดเกิดภายหลัง",
    "Symptomatic Carrier (A)": "พาหะที่มีอาการ (ฮีโมฟีเลีย เอ)",
    "Symptomatic Carrier (B)": "พาหะที่มีอาการ (ฮีโมฟีเลีย บี)",
    Severe: "รุนแรง",
    Moderate: "ปานกลาง",
    Mild: "เล็กน้อย",
    "Not known": "ไม่ทราบ",
    "Severe deficiency": "พร่องรุนแรง",
    "Partial deficiency": "พร่องบางส่วน",
    "Life-threatening / major bleeding": "อันตรายถึงชีวิต / เลือดออกรุนแรง",
    "Moderate / non-life-threatening": "ปานกลาง / ไม่อันตรายถึงชีวิต",
    Unknown: "ไม่ทราบ",

    "Handle with Care": "โปรดดูแลด้วยความระมัดระวัง",
    "Date of Birth": "วันเกิด",
    "Emergency Contact": "ผู้ติดต่อกรณีฉุกเฉิน",
    Contact: "ผู้ติดต่อ",
    "Call Emergency Contact": "โทรหาผู้ติดต่อกรณีฉุกเฉิน",
    "Primary Doctor (Organisation)": "แพทย์ประจำตัว (สถานพยาบาล)",
    Organisation: "สถานพยาบาล",
    "Yes — details not recorded": "มี — ไม่ได้บันทึกรายละเอียด",
    "Machine-translated from English": "แปลด้วยเครื่องจากภาษาอังกฤษ",
  },
  vi: {
    "Bleeding Disorder": "Rối loạn đông máu",
    "Blood Type": "Nhóm máu",
    Diagnosis: "Chẩn đoán",
    Severity: "Mức độ",
    "Current Medication": "Thuốc đang dùng",
    "Drug Allergies": "Dị ứng thuốc",
    Allergies: "Dị ứng",
    "Haemophilia A": "Hemophilia A",
    "Haemophilia B": "Hemophilia B",
    "Factor XI Deficiency": "Thiếu yếu tố XI",
    "Acquired Haemophilia": "Hemophilia mắc phải",
    "Symptomatic Carrier (A)": "Người mang gen có triệu chứng (Hemophilia A)",
    "Symptomatic Carrier (B)": "Người mang gen có triệu chứng (Hemophilia B)",
    Severe: "Nặng",
    Moderate: "Trung bình",
    Mild: "Nhẹ",
    "Not known": "Không rõ",
    "Severe deficiency": "Thiếu hụt nặng",
    "Partial deficiency": "Thiếu hụt một phần",
    "Life-threatening / major bleeding": "Đe dọa tính mạng / chảy máu nặng",
    "Moderate / non-life-threatening": "Trung bình / không đe dọa tính mạng",
    Unknown: "Không rõ",

    "Handle with Care": "Xử trí thận trọng",
    "Emergency Contact": "Liên hệ khẩn cấp",
    Contact: "Người liên hệ",
    "Call Emergency Contact": "Gọi liên hệ khẩn cấp",
    "Primary Doctor (Organisation)": "Bác sĩ điều trị (Cơ sở y tế)",
    Organisation: "Cơ sở y tế",
    "None recorded": "Không có ghi nhận",
    "Machine-translated from English": "Dịch máy từ tiếng Anh",
  },
  tl: {
    "Bleeding Disorder": "Karamdaman sa Pagdurugo",
    "Blood Type": "Uri ng Dugo",
    Diagnosis: "Diagnosis",
    Severity: "Kalubhaan",
    "Current Medication": "Kasalukuyang Gamot",
    "Drug Allergies": "Allergy sa Gamot",
    Allergies: "Mga Allergy",
    "Haemophilia A": "Hemophilia A",
    "Haemophilia B": "Hemophilia B",
    "Factor XI Deficiency": "Kakulangan sa Factor XI",
    "Acquired Haemophilia": "Nakuhang Hemophilia",
    "Symptomatic Carrier (A)": "Carrier na May Sintomas (Hemophilia A)",
    "Symptomatic Carrier (B)": "Carrier na May Sintomas (Hemophilia B)",
    Severe: "Malubha",
    Moderate: "Katamtaman",
    Mild: "Banayad",
    "Not known": "Hindi alam",
    "Severe deficiency": "Malubhang kakulangan",
    "Partial deficiency": "Bahagyang kakulangan",
    "Life-threatening / major bleeding": "Nagbabanta sa buhay / malubhang pagdurugo",
    "Moderate / non-life-threatening": "Katamtaman / hindi nagbabanta sa buhay",
    Unknown: "Hindi alam",

    "Handle with Care": "Mag-ingat sa Paghawak",
    "Emergency Contact": "Kontak sa Emerhensiya",
    Contact: "Kontak",
    "Call Emergency Contact": "Tawagan ang Kontak sa Emerhensiya",
    "Primary Doctor (Organisation)": "Pangunahing Doktor (Organisasyon)",
    Organisation: "Organisasyon",
    "Generated on": "Ginawa noong",
    "Machine-translated from English": "Isinalin ng makina mula sa Ingles",
  },
  ja: {
    "Bleeding Disorder": "出血性疾患",
    "Blood Type": "血液型",
    Diagnosis: "診断名",
    Severity: "重症度",
    "Current Medication": "使用中の薬剤",
    "Drug Allergies": "薬剤アレルギー",
    Allergies: "アレルギー",
    "Haemophilia A": "血友病A",
    "Haemophilia B": "血友病B",
    "Factor XI Deficiency": "第XI因子欠乏症",
    "Acquired Haemophilia": "後天性血友病",
    "Symptomatic Carrier (A)": "症候性保因者（血友病A）",
    "Symptomatic Carrier (B)": "症候性保因者（血友病B）",
    Severe: "重症",
    Moderate: "中等症",
    Mild: "軽症",
    "Not known": "不明",
    "Severe deficiency": "重度欠乏",
    "Partial deficiency": "部分欠乏",
    "Life-threatening / major bleeding": "生命に関わる／重大な出血",
    "Moderate / non-life-threatening": "中等度／生命に関わらない",
    Unknown: "不明",

    "Handle with Care": "慎重な対応を",
    "Patient Details": "患者情報",
    Name: "氏名",
    Relationship: "続柄",
    Contact: "連絡先",
    "Call Emergency Contact": "緊急連絡先に電話",
    "Primary Doctor (Organisation)": "主治医（医療機関）",
    Organisation: "医療機関",
    "Call Doctor": "医師に電話",
    "Not recorded": "未記録",
    "None recorded": "記録なし",
    "Yes — details not recorded": "あり（詳細は未記録）",
    "Generated on": "作成日",
    "Machine-translated from English": "英語から機械翻訳",
  },
  ko: {
    "Bleeding Disorder": "출혈성 질환",
    "Blood Type": "혈액형",
    Diagnosis: "진단명",
    Severity: "중증도",
    "Current Medication": "현재 사용 약물",
    "Drug Allergies": "약물 알레르기",
    Allergies: "알레르기",
    "Haemophilia A": "혈우병 A",
    "Haemophilia B": "혈우병 B",
    "Factor XI Deficiency": "제11인자 결핍증",
    "Acquired Haemophilia": "후천성 혈우병",
    "Symptomatic Carrier (A)": "증상성 보인자 (혈우병 A)",
    "Symptomatic Carrier (B)": "증상성 보인자 (혈우병 B)",
    Severe: "중증",
    Moderate: "중등증",
    Mild: "경증",
    "Not known": "알 수 없음",
    "Severe deficiency": "중증 결핍",
    "Partial deficiency": "부분 결핍",
    "Life-threatening / major bleeding": "생명 위협 / 주요 출혈",
    "Moderate / non-life-threatening": "중등도 / 생명 위협 없음",
    Unknown: "알 수 없음",

    "Handle with Care": "신중한 처치 필요",
    Name: "이름",
    Relationship: "관계",
    Phone: "전화번호",
    Contact: "연락처",
    "Call Emergency Contact": "긴급 연락처에 전화",
    "Primary Doctor (Organisation)": "주치의 (소속 기관)",
    Organisation: "소속 기관",
    Doctor: "의사",
    "Call Doctor": "의사에게 전화",
    "None recorded": "기록된 사항 없음",
    "Yes — details not recorded": "있음 (세부 사항 기록 없음)",
    "Generated on": "생성일",
    "Machine-translated from English": "영어에서 기계 번역됨",
  },
  hi: {
    "Bleeding Disorder": "रक्तस्राव विकार",
    "Blood Type": "रक्त समूह",
    Diagnosis: "निदान",
    Severity: "गंभीरता",
    "Current Medication": "वर्तमान दवाएँ",
    "Drug Allergies": "दवा से एलर्जी",
    Allergies: "एलर्जी",
    "Haemophilia A": "हीमोफीलिया ए",
    "Haemophilia B": "हीमोफीलिया बी",
    "Factor XI Deficiency": "फैक्टर XI की कमी",
    "Acquired Haemophilia": "अर्जित हीमोफीलिया",
    "Symptomatic Carrier (A)": "लक्षणयुक्त वाहक (हीमोफीलिया ए)",
    "Symptomatic Carrier (B)": "लक्षणयुक्त वाहक (हीमोफीलिया बी)",
    Severe: "गंभीर",
    Moderate: "मध्यम",
    Mild: "हल्का",
    "Not known": "ज्ञात नहीं",
    "Severe deficiency": "गंभीर कमी",
    "Partial deficiency": "आंशिक कमी",
    "Life-threatening / major bleeding": "जानलेवा / भारी रक्तस्राव",
    "Moderate / non-life-threatening": "मध्यम / जानलेवा नहीं",
    Unknown: "अज्ञात",

    "Handle with Care": "सावधानी से उपचार करें",
    "Call Emergency Contact": "आपातकालीन संपर्क को कॉल करें",
    "Call Doctor": "डॉक्टर को कॉल करें",
    "Generated on": "निर्माण तिथि",
    "Machine-translated from English": "अंग्रेज़ी से मशीनी अनुवाद",
  },
};
